apiVersion: apps/v1
kind: Deployment
metadata:
  name: d2cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d2cli
  template:
    metadata:
      labels:
        app: d2cli
    spec:
      containers:
        - name: d2cli
          image: ggibellato/ifsfc2d2cliprod
          ports:
            - containerPort: 80